# Generated by Django 3.1 on 2020-11-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
