# Generated by Django 3.1 on 2020-11-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
