# Generated by Django 3.1 on 2020-11-15 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0002_auto_20201114_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='help_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(verbose_name='내용')),
                ('region', models.CharField(max_length=50, verbose_name='도움 지역')),
                ('help_coin', models.IntegerField(verbose_name='코인 개수')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('help_date', models.DateTimeField(verbose_name='도움 요청일')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단고정')),
                ('finished', models.BooleanField(default=False, verbose_name='마감 여부')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
