# Generated by Django 3.1 on 2020-11-21 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages_Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unread_count', models.BooleanField(default=True, verbose_name='미확인 쪽지 수')),
                ('whohelp', models.BooleanField(default=True, verbose_name='도와준 사람')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='보낸 쪽지')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='받은 쪽지')),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('user1_send', models.BooleanField(default=True, verbose_name='보낸이')),
                ('didread', models.BooleanField(default=True, verbose_name='확인 여부')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dona.messages_container')),
            ],
        ),
    ]
