# Generated by Django 3.1 on 2020-11-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0003_help_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='help_board',
            name='region_last',
            field=models.CharField(max_length=20, null=True, verbose_name='도움 지역 읍면동'),
        ),
    ]
