# Generated by Django 3.1 on 2020-11-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0004_messages_messages_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_id',
            new_name='message',
        ),
    ]
