# Generated by Django 3.1 on 2020-11-18 21:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0004_help_board_region_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='help_board',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
