# Generated by Django 3.1 on 2020-11-21 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0005_auto_20201121_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user1_send',
            new_name='user_send',
        ),
        migrations.RemoveField(
            model_name='messages_container',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messages_container',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='messages_container',
            name='whohelp',
        ),
        migrations.AddField(
            model_name='messages_container',
            name='userone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='도움 받을 사람'),
        ),
        migrations.AddField(
            model_name='messages_container',
            name='usertwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='도와줄 사람'),
        ),
        migrations.AlterField(
            model_name='messages_container',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='미확인 쪽지 수'),
        ),
    ]
