# Generated by Django 3.1 on 2020-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0006_auto_20201121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(max_length=200, verbose_name='쪽지'),
        ),
    ]
