# Generated by Django 3.1 on 2020-11-18 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help_board',
            name='help_coin',
            field=models.IntegerField(default=10, verbose_name='코인 개수'),
        ),
        migrations.AlterField(
            model_name='help_board',
            name='help_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='도움 요청일'),
        ),
    ]
