# Generated by Django 3.1 on 2020-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0007_auto_20201123_1928'),
    ]

    operations = [
    ]
