# Generated by Django 3.1 on 2020-11-19 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0008_auto_20201118_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='help_board',
            name='help_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Dona 요청일'),
        ),
    ]
