# Generated by Django 3.1 on 2020-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0008_auto_20201123_1948'),
    ]

    operations = [
    ]
